name: Build and Push Docker Image to DO Registry

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-push:
    name: Build & Push Docker Image to DigitalOcean Registry
    runs-on: ubuntu-22.04

    env:
      IMAGE_NAME: ${{ vars.DO_REGISTRY }}/${{ github.event.repository.name }}
      IMAGE_VERSION: ${{ github.ref_name }}

    steps:
      - name: Prepare Environment Variables
        run: |
          echo "IMAGE_VERSION=${IMAGE_VERSION#v}" >> $GITHUB_ENV
          echo "IMAGE_NAME_VERSIONED=${IMAGE_NAME}:${IMAGE_VERSION#v}" >> $GITHUB_ENV

      - name: Test
        run: |
      - uses: actions/checkout@v3
      - name: Setup Java 17 JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Setup DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl registry login

#      - name: Build Docker Image
#        run: |
#          echo "Building image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ..."
#          ./gradlew clean bootBuildImage --imageName="${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}" --quiet --no-daemon

#      - name: Tag Docker Image with 'latest' and Push to DO Registry
#        run: |
#          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.IMAGE_NAME }}:latest
#          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
#          docker push ${{ env.IMAGE_NAME }}:latest