name: Build & Push Docker Image to Container Registry

on:
  release:
    types:
      - created
    tags:
      - '[vV]?[0-9]+(\.[0-9]+)*(\.[0-9]+)?(-[a-zA-Z0-9]+)?'

jobs:
  build-push:
    name: Publish Image to Container Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Push Image to Registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY || '' }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME || '' }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD || '' }}
          DOCKER_URL: ${{ vars.DOCKER_URL  || '' }} #Optional - Default: Docker Hub
          BUILDER_PACKAGE: ${{ vars.BUILDER_PACKAGE || '' }} #Optional - Default: Spring Boot logic
          TAG_LATEST: ${{ vars.TAG_LATEST || 'true' }} #Optional - Default: TRUE
          IMAGE_NAME: ${{ github.event.repository.name }} #Optional - Default: rootProject.name
          IMAGE_VERSION: ${{ github.ref_name || '' }} #Optional - Default: project.version
        run: ./gradlew clean bootBuildImage --quiet --no-daemon