name: Build and Push Docker Image to DO Registry

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-push:
    name: Build & Push Docker Image to DigitalOcean Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare Environment Variables
        run: |
          version=${{ github.ref_name }}
          imageName=${{ vars.DO_REGISTRY }}/${{ github.event.repository.name }}
          echo "IMAGE_NAME_LATEST=${imageName}:latest" >> $GITHUB_ENV
          echo "IMAGE_NAME_VERSION=${imageName}:${version#v}" >> $GITHUB_ENV
          echo "IMAGE_NAME_VERSION: ${{ env.IMAGE_NAME_VERSION }}"
          echo "IMAGE_NAME_LATEST: ${{ env.IMAGE_NAME_LATEST }}"

      - uses: actions/checkout@v3
      - name: Setup Java 17 JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Setup DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - run: doctl registry login

      - name: Build Docker Image
        run: |
          echo "Building image ${{ env.IMAGE_NAME_VERSION }} ..."
          ./gradlew clean bootBuildImage --imageName="${{ env.IMAGE_NAME_VERSION }}" --quiet --no-daemon

      - name: Push version Docker Image to DigitalOcean Registry
        run: docker push ${{ env.IMAGE_NAME_VERSION }}

      - name: Tag 'latest' and push Docker Image to DigitalOcean Registry
        run: |
          docker tag  ${{ env.IMAGE_NAME_VERSION }} ${{ env.IMAGE_NAME_LATEST }}
          docker push ${{ env.IMAGE_NAME_LATEST }}