name: Build

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ${{ vars.DO_REGISTRY }}
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ vars.DO_REGISTRY }}/${{ github.event.repository.name }}
  IMAGE_VERSION_TEST: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Current variables
        run: |
          echo "REGISTRY: REGISTRY"
          echo "REPO_NAME: $REPO_NAME"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_VERSION_TEST: $IMAGE_VERSION_TEST"

#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Setup JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: temurin
#          cache: gradle

#      - name: Setup DigitalOcean CLI
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DO_TOKEN }}

#      - name: Extract Version from Release Tag
#        id: extract-version-tag
#        run: |
#          echo "version_tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

#      - name: Build Docker Image
#        id: build-image
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
#        run: |
#          ./gradlew clean bootBuildImage --imageName="$IMAGE_NAME:${{ steps.extract-version-tag.outputs.version_tag }}" --quiet

#      - name: Publish to DigitalOcean Registry
#        run: |
#          doctl registry login
#          docker push $IMAGE_NAME:${{ steps.extract-version-tag.outputs.version_tag }}
#          docker tag $IMAGE_NAME:${{ steps.extract-version-tag.outputs.version_tag }} $IMAGE_NAME:latest
#          docker push $IMAGE_NAME:latest