name: Build

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ${{ vars.DO_REGISTRY }}
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME_TEST: "$REGISTRY/$REPO_NAME"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Current variables
        run: |
          echo "REGISTRY: REGISTRY"
          echo "REPO_NAME: $REPO_NAME"
          echo "IMAGE_NAME_TEST: $IMAGE_NAME_TEST"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Extract Version from Release Tag
        id: extract-version-tag
        run: |
          echo "version_tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        id: build-image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          IMAGE_VERSION: ${{ steps.extract-version-tag.outputs.version_tag }}
        run: |
          image_name=$REGISTRY/$REPO_NAME:$IMAGE_VERSION
          ./gradlew clean bootBuildImage --imageName="$image_name" --quiet
          echo "image_name=$image_name" >> $GITHUB_OUTPUT

      - name: Prepare DigitalOcean CLI (doctl)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Publish to DigitalOcean Registry
        env:
          IMAGE_NAME: ${{ steps.build-image.outputs.image_name }}
        run: |
          doctl registry login
          docker push $IMAGE_NAME
          docker tag $IMAGE_NAME $REGISTRY/$REPO_NAME:latest
          docker push $REGISTRY/$REPO_NAME:latest