name: Build and Push Docker Image to DO Registry

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-push:
    name: Build & Push Docker Image to DigitalOcean Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare Environment Variables
        run: |
          version=${{ github.ref_name }}
          imageName=${{ vars.DO_REGISTRY }}/${{ github.event.repository.name }}          
          echo "IMAGE_NAME_VERSION=${imageName}:latest" >> $GITHUB_ENV
          echo "IMAGE_NAME_LATEST=${imageName}:${version#v}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo "Image Name latest: ${{ env.IMAGE_NAME_LATEST }}"
          echo "Image Name versioned: ${{ env.IMAGE_NAME_VERSION }}"

#      - uses: actions/checkout@v3
#      - name: Setup Java 17 JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'liberica'
#          cache: 'gradle'

#      - name: Setup DigitalOcean CLI
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DO_TOKEN }}
#      - run: doctl registry login

#      - name: Build Docker Image
#        run: |
#          echo "Building image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ..."
#          ./gradlew clean bootBuildImage --imageName="${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}" --quiet --no-daemon

#      - name: Tag Docker Image with 'latest' and Push to DO Registry
#        run: |
#          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ${{ env.IMAGE_NAME }}:latest
#          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
#          docker push ${{ env.IMAGE_NAME }}:latest