name: Build

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Extract Version from Release Tag
        id: extract-version-tag
        run: |
          echo "version_tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        id: build-image
        env:
          IMAGE_GROUP: ${{ secrets.IMAGE_GROUP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ steps.extract-version-tag.outputs.version_tag }}
        run: |
          image_name=registry.digitalocean.com/$IMAGE_GROUP/$REPO_NAME:$IMAGE_VERSION
          ./gradlew clean bootBuildImage --imageName="$image_name" --quiet
          echo "image_name=$image_name" >> $GITHUB_OUTPUT

      - name: Publish to DigitalOcean Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
        env:
          IMAGE_GROUP: ${{ env.IMAGE_GROUP }}
          REPO_NAME: ${{ github.event.repository.name }}
          IMAGE_NAME: ${{ steps.build-image.outputs.image_name }}
        run: |
          doctl registry login
          docker push $IMAGE_NAME
          docker tag $IMAGE_NAME registry.digitalocean.com/$IMAGE_GROUP/$REPO_NAME:latest
          docker push registry.digitalocean.com/$IMAGE_GROUP/$REPO_NAME:latest