name: Build and Push Docker Image to DO Registry

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-push:
    name: Build & Push Docker Image to DigitalOcean Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare Environment Variables
        run: |
          version=${{ github.ref_name }}
          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${version#v}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
      - name: Setup Java 17 JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'gradle'

#      - name: Setup DigitalOcean CLI
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DO_TOKEN }}

#      - name: Login to DigitalOcean Registry
#        run: doctl registry login --expiry-seconds=300

      - name: Build and Push Docker Image to DO Registry
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          TAG_LATEST: ${{ vars.TAG_LATEST }}
          DOCKER_USERNAME: ${{ secrets.DO_TOKEN }}
          DOCKER_PASSWORD: ${{ secrets.DO_TOKEN }}
          IMAGE_NAME: ${{ github.event.repository.name }}
          IMAGE_VERSION: ${{ env.RELEASE_VERSION }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "Building image ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} ..."
          ./gradlew clean bootBuildImage --quiet --no-daemon
#
#      - name: Push version Docker Image to DigitalOcean Registry
#        run: docker push ${{ env.IMAGE_NAME_VERSION }}

#      - name: Tag 'latest' and push Docker Image to DigitalOcean Registry
#        run: |
#          docker tag  ${{ env.IMAGE_NAME_VERSION }} ${{ env.IMAGE_NAME_LATEST }}
#          docker push ${{ env.IMAGE_NAME_LATEST }}

#      - name: Logout of DigitalOcean Registry
#        run: doctl registry logout