name: Build and Push Docker Image to DO Registry

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: ${{ vars.DO_REGISTRY }}/${{ github.event.repository.name }}
  IMAGE_VERSION: ${{ github.ref_name }}

jobs:

  build-push:
    name: Build & Push Docker Image to DigitalOcean Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare Image Version
        run: |
          echo "IMAGE_VERSION=${IMAGE_VERSION#v}" >> $GITHUB_ENV
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_VERSION: $IMAGE_VERSION"

#      - uses: actions/checkout@v3
#      - name: Setup Java 17 JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'liberica'
#          check-latest: true
#          cache: 'gradle'

#      - name: Setup DigitalOcean CLI
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DO_TOKEN }}

#      - name: Login to DigitalOcean Registry
#        run: doctl registry login

#      - name: Build Docker Image
#        run: |
#          echo "Building image $IMAGE_NAME:$IMAGE_VERSION ..."
#          ./gradlew clean bootBuildImage --imageName="$IMAGE_NAME:$IMAGE_VERSION" --quiet --no-daemon

#      - name: Tag Docker Image with 'latest' and Push to DO Registry
#        run: |
#          docker tag "$IMAGE_NAME:$IMAGE_VERSION" "$IMAGE_NAME":latest
#          docker push "$IMAGE_NAME"