name: Build and Push Docker Image to DO Registry

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: ${{ vars.DO_REGISTRY }}/${{ github.event.repository.name }}
  IMAGE_VERSION: ${{ github.ref_name }}

jobs:
  build-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: Prepare Variables
        run: |
          echo "IMAGE_VERSION=${IMAGE_VERSION#v}" >> $GITHUB_ENV
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_VERSION: $IMAGE_VERSION"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Setup DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Build Docker Image
        id: build-image
        run: |
          echo "Building image $IMAGE_NAME:$IMAGE_VERSION ..."
          ./gradlew clean bootBuildImage --imageName="$IMAGE_NAME:$IMAGE_VERSION" --quiet

      - name: Login to DigitalOcean Registry
        run: doctl registry login

#      - name: Publish to DigitalOcean Registry
#        run: |
#          echo "Pushing $IMAGE_NAME:$IMAGE_VERSION to Container Registry ..."
#          docker push $IMAGE_NAME:$IMAGE_VERSION
#          echo "Tagging $IMAGE_NAME:$IMAGE_VERSION with 'latest' and pushing $IMAGE_NAME:latest to Container Registry ..."
#          docker tag $IMAGE_NAME:$IMAGE_VERSION $IMAGE_NAME:latest && docker push $IMAGE_NAME:latest
