name: Build and Push Docker Image to Docker Registry

on:
  release:
    types:
      - created
    tags:
      - '[vV]?[0-9]+(\.[0-9]+)*(\.[0-9]+)?(-[a-zA-Z0-9]+)?'

jobs:
  build-push:
    name: Build & Push Docker Image to DigitalOcean Registry
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Push Docker Image to DO Registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_URL: ${{ vars.DO_REGISTRY_URL }} #Optional - Default: Docker Hub
          IMAGE_NAME: ${{ github.event.repository.name }} #Optional - Default: rootProject.name
          IMAGE_VERSION: ${{ github.ref_name }} #Optional - Default: project.version
          #BUILDER_PACKAGE: "paketobuildpacks/builder-jammy-base:0.4.172" #Optional - Default: Spring Boot logic
        run: ./gradlew clean bootBuildImage --quiet --no-daemon