name: Build

on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Extract Version from Tag
        id: extract-version
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Run Gradle Command
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          IMAGE_VERSION: ${{ steps.extract-version.outputs.version }}
        run: ./gradlew clean bootBuildImage